image: bash

pages:
  artifacts:
    paths:
       - public
  script:
    - mkdir -p public/images
    - cp web/index.html public/index.html
    - cp web/images/icon.ico public/images/icon.ico
    - cp web/images/logo.webp public/images/logo.webp
    - gzip -9 -c web/index.html > web/index.html.gz
    - gzip -9 -c web/images/icon.ico > web/images/icon.ico.gz
    - gzip -9 -c web/images/logo.webp > public/images/logo.webp.gz
