#!/usr/bin/env bash

. generated.env  # <------ load for CXX and LD FLAGS

SOURCE=$1

CXX=${CXX:-clang++}

if [ -z $SOURCE ]; then echo 'No source'; exit 1; fi

echo "$0: [runtime::build]"

# shellcheck disable=SC2164
cd ./runtime && make && ln -sf libChiakiLispRuntime.so libchiakilisp.so && cd -

SRC_FILENAME="./generated.cpp"
BIN_FILENAME="./generated"

CXX_FLAGS="-Iruntime -std=c++20"
LD_FLAGS="-Lruntime -lchiakilisp"

export LD_LIBRARY_PATH+=":runtime"

echo "$0: [source::compile-and-then-execute]"

CHIAKILISP__COMPILER_MODE=1 ./chiakilang $SOURCE \
  && $CXX $CXX_FLAGS $LD_FLAGS $SRC_FILENAME -o $BIN_FILENAME && $BIN_FILENAME