#!/usr/bin/env bash

SOURCE=$1

if [ -z $SOURCE ]; then echo 'No source'; exit 1; fi

export CXX=${CXX:-clang++}

if [ "$REBUILD_RUNTIME" == "1" ]; then
  ./build-cxx-runtime.sh
fi

SRC_FILENAME="./generated.cpp"
BIN_FILENAME="./generated"

echo "Chiakilisp Compiler Script"
echo "    => Source File Name: $SOURCE"
echo "    => Backend: $CXX"
echo "    => Arguments To Executable:" ${@:2}

CHIAKILISP__COMPILER_MODE=1 ./chiakilang $SOURCE && clang-format -i generated.cpp \
  && . generated.env \
  && $CXX -std=c++20 -pipe $CXX_FLAGS -Iruntime \
          -Lruntime $LD_FLAGS -lchiakilisp $SRC_FILENAME -o $BIN_FILENAME && $BIN_FILENAME ${@:2}